---
name: checkov

on:
  pull_request:

jobs:
  scan:
    permissions:
      contents: read
      security-events: read
      actions: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli
          output_file_path: console
          skip_path: "./"
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
        continue-on-error: true
...